language: rust

rust:
  - stable
  - beta
  - nightly

env:
  - DATABASE_NAME=boilerplateapp DATABASE_URL=postgres://localhost/boilerplateapp

services:
  - postgresql

matrix:
  allow_failures:
    - rust: stable
    - rust: beta

before_script:
  - cargo install --force diesel_cli
  - cp .env.example .env
  - ./reset.sh

script:
  - cargo build --verbose
  - cargo test --verbose

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly && "$TRAVIS_OS_NAME" == "linux" ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
